# Generated by Django 3.2.11 on 2022-04-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacite.identifier'),
        ),
    ]
