# Generated by Django 3.2.11 on 2022-04-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0003_add_geo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_number', models.CharField(blank=True, max_length=256)),
                ('award_uri', models.URLField(blank=True)),
                ('award_title', models.CharField(blank=True, max_length=256)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacite.name')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacite.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='funding_references',
            field=models.ManyToManyField(blank=True, related_name='resources_as_funding_reference', through='datacite.FundingReference', to='datacite.Name'),
        ),
    ]
