# Generated by Django 3.2.11 on 2022-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0005_add_related_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
