# Generated by Django 3.2.11 on 2022-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0006_resource_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateidentifier',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creator',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relatedidentifier',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
