# Generated by Django 3.2.16 on 2023-01-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0007_use_integer_field_for_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternateidentifier',
            options={'ordering': ('resource', 'order', 'identifier__citation')},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ('date_type',)},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ('description_type',)},
        ),
        migrations.AlterModelOptions(
            name='relatedidentifier',
            options={'ordering': ('resource', 'order', 'identifier__citation')},
        ),
        migrations.AlterModelOptions(
            name='rights',
            options={'ordering': ('rights_identifier',), 'verbose_name_plural': 'Rights'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('title_type',)},
        ),
    ]
