# Generated by Django 3.2.16 on 2023-02-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0008_change_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ('order', 'name__family_name', 'name__name')},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ('order', 'name__family_name', 'name__name')},
        ),
    ]
