# Generated by Django 3.2.18 on 2023-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0010_subjects_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('subject',)},
        ),
    ]
