# Generated by Django 3.2.18 on 2023-02-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0011_alter_subject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ('geo_location_place',)},
        ),
    ]
