name: pytest

on: ['push']

jobs:
  pytest:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.7', '3.11']

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install psycopg2-binary
        python3 -m pip install coveralls
        python3 -m pip install -r requirements/pytest.txt
        python3 -m pip install .

    - name: Setup environment file
      run: |
        echo "SECRET_KEY=thisisnotaverysecretkey" >> $GITHUB_ENV
        echo "DATABASE=postgresql://postgres:postgres_password@localhost/django_datacite" >> $GITHUB_ENV

    - name: Run pytest
      run: |
        pytest --cov=django_datacite

    - name: Run coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ join(matrix.*, '-') }}
        parallel: true

  coveralls:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
    - name: Run coveralls finish
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        carryforward: "run-3.7,run-3.11"
